name: Deploy kafka-manager to prod
on:
  push:
    paths:
      - "kafka-manager/prod/*.yaml"

jobs:
  deploy-dev:
    name: Deploy kafka-manager to prod
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: List resource files
        run: echo "RESOURCE_FILES=$(find kafka-manager/prod -type f | tr '\n' ',' | sed 's/,$/\n/')" >> $GITHUB_ENV
      - name: Deploy application
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: ${{ env.RESOURCE_FILES }}
          PRINT_PAYLOAD: true
