name: Deploy kafka topics to dev
on:
  push:
    paths:
      - "kafka-topic/dev/*.yaml"

jobs:
  deploy-dev:
    name: Deploy kafka topics to dev
    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: List resource files
        run: echo "RESOURCE_FILES=$(find kafka-topic/dev -type f | tr '\n' ',' | sed 's/,$/\n/')" >> $GITHUB_ENV
      - name: Deploy kafka topics
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: ${{ env.RESOURCE_FILES }}
          PRINT_PAYLOAD: true
